#!/bin/sh
VPN_NAME="PLACEHOLDER"

interface=$1 status=$2
case $status in
  up|vpn-down)
	if ! (nmcli connection show --active | grep "$VPN_NAME"); then
	  nmcli connection up id "$VPN_NAME";
	fi
    ;;
esac
